
[0m20:54:01.452624 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd668194eb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd66a222520>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd66a7b3c40>]}


============================== 20:54:01.483552 | 01093599-4eee-4bd3-8653-97d31f123c77 ==============================
[0m20:54:01.483552 [info ] [MainThread]: Running with dbt=1.8.7
[0m20:54:01.484703 [debug] [MainThread]: running dbt with arguments {'fail_fast': 'False', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'debug': 'False', 'log_format': 'default', 'use_experimental_parser': 'False', 'profiles_dir': '/Users/zubairlakhia/.dbt', 'static_parser': 'True', 'no_print': 'None', 'introspect': 'True', 'use_colors': 'True', 'quiet': 'False', 'printer_width': '80', 'empty': 'False', 'partial_parse': 'True', 'invocation_command': 'dbt run --select temp_wnba_viz.sql', 'write_json': 'True', 'warn_error': 'None', 'indirect_selection': 'eager', 'log_path': 'logs', 'send_anonymous_usage_stats': 'True', 'version_check': 'True', 'log_cache_events': 'False', 'cache_selected_only': 'False'}
[0m20:54:01.485923 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/zubairlakhia/Desktop/team_23/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:54:01.488527 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.1950799, "process_user_time": 1.626895, "process_kernel_time": 0.462401, "process_mem_max_rss": "84627456", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m20:54:01.489494 [debug] [MainThread]: Command `dbt run` failed at 20:54:01.489338 after 0.20 seconds
[0m20:54:01.490050 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd668194eb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd66a62a940>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd66a76fc70>]}
[0m20:54:01.490628 [debug] [MainThread]: Flushing usage events
[0m21:41:16.313128 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1050574f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106a942b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106a94bb0>]}


============================== 21:41:16.321985 | 2108584b-0aba-4b87-9b1c-09cf7a27ebf2 ==============================
[0m21:41:16.321985 [info ] [MainThread]: Running with dbt=1.8.8
[0m21:41:16.323865 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/zubairlakhia/.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt run --select temp_wnba_viz.sql', 'send_anonymous_usage_stats': 'True'}
[0m21:41:16.325685 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/zubairlakhia/Desktop/team_23/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m21:41:16.443122 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.32002142, "process_user_time": 2.594338, "process_kernel_time": 0.463373, "process_mem_max_rss": "88518656", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m21:41:16.446920 [debug] [MainThread]: Command `dbt run` failed at 21:41:16.446550 after 0.33 seconds
[0m21:41:16.448896 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1050574f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106a69280>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106a94160>]}
[0m21:41:16.450444 [debug] [MainThread]: Flushing usage events
